apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-a46o
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/test-rhtap-84-tenant/test-rhtap-84-app/devfile-sample-code-with-quarkus-a46o@sha256:a06c32021fe0d0a30efff9f8736f93bfadd120c0b5ba7ff67bcc908850accd18
        name: my-java-quarkus
        resources: {}
status: {}
